"""eliminar_estado_venta

Revision ID: 0d9792b58905
Revises: e6ce9f74eba3
Create Date: 2026-06-06 23:14:08.800576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d9792b58905'
down_revision: Union[str, Sequence[str], None] = 'e6ce9f74eba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'estado_venta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('estado_venta', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
