"""agregar_estado_venta

Revision ID: 3c8838755737
Revises: 8c159fbdb412
Create Date: 2026-06-16 22:00:34.234124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8838755737'
down_revision: Union[str, Sequence[str], None] = '8c159fbdb412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('estado_venta', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'estado_venta')
    # ### end Alembic commands ###
