"""agregar_items_anulados_json

Revision ID: 661f75fb03ca
Revises: 3c8838755737
Create Date: 2026-06-17 19:45:45.080680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661f75fb03ca'
down_revision: Union[str, Sequence[str], None] = '3c8838755737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_consignacion', sa.Column('items_anulados_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos_consignacion', 'items_anulados_json')
    # ### end Alembic commands ###
