"""eliminar_ubicacion_str_stock_configs

Revision ID: 8c159fbdb412
Revises: f913f16fb77b
Create Date: 2026-06-08 19:32:16.290445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c159fbdb412'
down_revision: Union[str, Sequence[str], None] = 'f913f16fb77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_configs', 'ubicacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_configs', sa.Column('ubicacion', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
