"""add_venta_id_to_gastos

Revision ID: d4190e75c423
Revises: 661f75fb03ca
Create Date: 2026-06-24 01:12:49.634504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4190e75c423'
down_revision: Union[str, Sequence[str], None] = '661f75fb03ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('venta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gastos', 'ventas', ['venta_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gastos', type_='foreignkey')
    op.drop_column('gastos', 'venta_id')
    # ### end Alembic commands ###
