"""agregar_columna_devuelto_detalles

Revision ID: e5f54c1e5c1b
Revises: 0d9792b58905
Create Date: 2026-06-07 11:26:35.917685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f54c1e5c1b'
down_revision: Union[str, Sequence[str], None] = '0d9792b58905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_venta', sa.Column('devuelto', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalles_venta', 'devuelto')
    # ### end Alembic commands ###
