"""agregar_fechas_seguimiento_ventas

Revision ID: e6ce9f74eba3
Revises: f3c49f5cef15
Create Date: 2026-06-06 22:05:31.614028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6ce9f74eba3'
down_revision: Union[str, Sequence[str], None] = 'f3c49f5cef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'precio_compra')
    op.drop_column('productos', 'lugar_compra')
    op.drop_column('productos', 'fecha_compra')
    op.add_column('ventas', sa.Column('fecha_finalizado', sa.DateTime(), nullable=True))
    op.add_column('ventas', sa.Column('fecha_cancelado', sa.DateTime(), nullable=True))
    op.add_column('ventas', sa.Column('fecha_devuelto', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'fecha_devuelto')
    op.drop_column('ventas', 'fecha_cancelado')
    op.drop_column('ventas', 'fecha_finalizado')
    op.add_column('productos', sa.Column('fecha_compra', sa.DATE(), nullable=True))
    op.add_column('productos', sa.Column('lugar_compra', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('productos', sa.Column('precio_compra', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
