"""inmutabilidad_pagos_consignacion

Revision ID: f913f16fb77b
Revises: e5f54c1e5c1b
Create Date: 2026-06-08 19:02:22.627361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f913f16fb77b'
down_revision: Union[str, Sequence[str], None] = 'e5f54c1e5c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos_consignacion', sa.Column('estado', sa.String(length=50), nullable=True))
    op.add_column('pagos_consignacion', sa.Column('motivo_anulacion', sa.Text(), nullable=True))
    op.add_column('pagos_consignacion', sa.Column('fecha_anulacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos_consignacion', 'fecha_anulacion')
    op.drop_column('pagos_consignacion', 'motivo_anulacion')
    op.drop_column('pagos_consignacion', 'estado')
    # ### end Alembic commands ###
